Traceback (most recent call last):
  File "C:\Users\rubde\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\rubde\anaconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\rubde\anaconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\rubde\anaconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\rubde\anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\rubde\anaconda3\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\rubde\anaconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\rubde\anaconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Define the ODE function (given q, return dq)
def q_dot(t,q):
    displ = q[0:N]
    velos = q[N:2*N]
    accel = np.linalg.inv(M).dot((Fvec(t)+K.dot(displ)+0.1*K.dot(velos))) #0.1 is damping factor, can change
    dq = np.zeros((2*N,))
    dq[0:N] = velos
    dq[N:2*N] = accel
    return dq

# Define initial state
q0 = np.zeros(2*N)

# Define time interval and time evaluation points
t0 = 0
tf = 100.0
nt = 50
tspan = np.linspace(t0,tf,nt+1)

# Solve (we use Radau method because the ODE is very stiff and it works best for this case)
sol = solve_ivp(fun=q_dot,t_span=[t0,tf],y0=q0,t_eval=tspan,method='Radau')

# Plot in local mode -- creates animated plot
import time
import pylab as pl
from IPython import display
for i in range(0,len(tspan)):
    #fig,ax = plt.subplots()
    display.clear_output(wait=True)
    #display.display(pl.gcf())
    plt.plot(np.linspace(0,L,N),sol.y[0:N,i])
    plt.ylim((-0.015,0.015))
    plt.xlabel("Beam position [m]")
    plt.ylabel("Displacement [m]")
    plt.title("Beam displacement animation")
    plt.savefig(f"../images/w3_t1_gif/shot{i+1}.png")
    time.sleep(0.05)
    plt.show()
    

------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mFileNotFoundError[0m                         Traceback (most recent call last)
[1;32m~\AppData\Local\Temp\ipykernel_154672\3947928116.py[0m in [0;36m<module>[1;34m[0m
[0;32m     34[0m     [0mplt[0m[1;33m.[0m[0mylabel[0m[1;33m([0m[1;34m"Displacement [m]"[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m     35[0m     [0mplt[0m[1;33m.[0m[0mtitle[0m[1;33m([0m[1;34m"Beam displacement animation"[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 36[1;33m     [0mplt[0m[1;33m.[0m[0msavefig[0m[1;33m([0m[1;34mf"../images/w3_t1_gif/shot{i+1}.png"[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     37[0m     [0mtime[0m[1;33m.[0m[0msleep[0m[1;33m([0m[1;36m0.05[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m     38[0m     [0mplt[0m[1;33m.[0m[0mshow[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\anaconda3\lib\site-packages\matplotlib\pyplot.py[0m in [0;36msavefig[1;34m(*args, **kwargs)[0m
[0;32m    977[0m [1;32mdef[0m [0msavefig[0m[1;33m([0m[1;33m*[0m[0margs[0m[1;33m,[0m [1;33m**[0m[0mkwargs[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m    978[0m     [0mfig[0m [1;33m=[0m [0mgcf[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 979[1;33m     [0mres[0m [1;33m=[0m [0mfig[0m[1;33m.[0m[0msavefig[0m[1;33m([0m[1;33m*[0m[0margs[0m[1;33m,[0m [1;33m**[0m[0mkwargs[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    980[0m     [0mfig[0m[1;33m.[0m[0mcanvas[0m[1;33m.[0m[0mdraw_idle[0m[1;33m([0m[1;33m)[0m   [1;31m# need this if 'transparent=True' to reset colors[0m[1;33m[0m[1;33m[0m[0m
[0;32m    981[0m     [1;32mreturn[0m [0mres[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\anaconda3\lib\site-packages\matplotlib\figure.py[0m in [0;36msavefig[1;34m(self, fname, transparent, **kwargs)[0m
[0;32m   3044[0m                         ax.patch._cm_set(facecolor='none', edgecolor='none'))
[0;32m   3045[0m [1;33m[0m[0m
[1;32m-> 3046[1;33m             [0mself[0m[1;33m.[0m[0mcanvas[0m[1;33m.[0m[0mprint_figure[0m[1;33m([0m[0mfname[0m[1;33m,[0m [1;33m**[0m[0mkwargs[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   3047[0m [1;33m[0m[0m
[0;32m   3048[0m     def ginput(self, n=1, timeout=30, show_clicks=True,

[1;32m~\anaconda3\lib\site-packages\matplotlib\backend_bases.py[0m in [0;36mprint_figure[1;34m(self, filename, dpi, facecolor, edgecolor, orientation, format, bbox_inches, pad_inches, bbox_extra_artists, backend, **kwargs)[0m
[0;32m   2317[0m                 [1;31m# force the figure dpi to 72), so we need to set it again here.[0m[1;33m[0m[1;33m[0m[0m
[0;32m   2318[0m                 [1;32mwith[0m [0mcbook[0m[1;33m.[0m[0m_setattr_cm[0m[1;33m([0m[0mself[0m[1;33m.[0m[0mfigure[0m[1;33m,[0m [0mdpi[0m[1;33m=[0m[0mdpi[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 2319[1;33m                     result = print_method(
[0m[0;32m   2320[0m                         [0mfilename[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[0;32m   2321[0m                         [0mfacecolor[0m[1;33m=[0m[0mfacecolor[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\anaconda3\lib\site-packages\matplotlib\backend_bases.py[0m in [0;36mwrapper[1;34m(*args, **kwargs)[0m
[0;32m   1646[0m             [0mkwargs[0m[1;33m.[0m[0mpop[0m[1;33m([0m[0marg[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1647[0m [1;33m[0m[0m
[1;32m-> 1648[1;33m         [1;32mreturn[0m [0mfunc[0m[1;33m([0m[1;33m*[0m[0margs[0m[1;33m,[0m [1;33m**[0m[0mkwargs[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1649[0m [1;33m[0m[0m
[0;32m   1650[0m     [1;32mreturn[0m [0mwrapper[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\anaconda3\lib\site-packages\matplotlib\_api\deprecation.py[0m in [0;36mwrapper[1;34m(*inner_args, **inner_kwargs)[0m
[0;32m    413[0m                          [1;32melse[0m [0mdeprecation_addendum[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[0;32m    414[0m                 **kwargs)
[1;32m--> 415[1;33m         [1;32mreturn[0m [0mfunc[0m[1;33m([0m[1;33m*[0m[0minner_args[0m[1;33m,[0m [1;33m**[0m[0minner_kwargs[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    416[0m [1;33m[0m[0m
[0;32m    417[0m     [0mDECORATORS[0m[1;33m[[0m[0mwrapper[0m[1;33m][0m [1;33m=[0m [0mdecorator[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py[0m in [0;36mprint_png[1;34m(self, filename_or_obj, metadata, pil_kwargs, *args)[0m
[0;32m    539[0m         """
[0;32m    540[0m         [0mFigureCanvasAgg[0m[1;33m.[0m[0mdraw[0m[1;33m([0m[0mself[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 541[1;33m         mpl.image.imsave(
[0m[0;32m    542[0m             [0mfilename_or_obj[0m[1;33m,[0m [0mself[0m[1;33m.[0m[0mbuffer_rgba[0m[1;33m([0m[1;33m)[0m[1;33m,[0m [0mformat[0m[1;33m=[0m[1;34m"png"[0m[1;33m,[0m [0morigin[0m[1;33m=[0m[1;34m"upper"[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[0;32m    543[0m             dpi=self.figure.dpi, metadata=metadata, pil_kwargs=pil_kwargs)

[1;32m~\anaconda3\lib\site-packages\matplotlib\image.py[0m in [0;36mimsave[1;34m(fname, arr, vmin, vmax, cmap, format, origin, dpi, metadata, pil_kwargs)[0m
[0;32m   1673[0m         [0mpil_kwargs[0m[1;33m.[0m[0msetdefault[0m[1;33m([0m[1;34m"format"[0m[1;33m,[0m [0mformat[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1674[0m         [0mpil_kwargs[0m[1;33m.[0m[0msetdefault[0m[1;33m([0m[1;34m"dpi"[0m[1;33m,[0m [1;33m([0m[0mdpi[0m[1;33m,[0m [0mdpi[0m[1;33m)[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 1675[1;33m         [0mimage[0m[1;33m.[0m[0msave[0m[1;33m([0m[0mfname[0m[1;33m,[0m [1;33m**[0m[0mpil_kwargs[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1676[0m [1;33m[0m[0m
[0;32m   1677[0m [1;33m[0m[0m

[1;32m~\anaconda3\lib\site-packages\PIL\Image.py[0m in [0;36msave[1;34m(self, fp, format, **params)[0m
[0;32m   2315[0m                 [0mfp[0m [1;33m=[0m [0mbuiltins[0m[1;33m.[0m[0mopen[0m[1;33m([0m[0mfilename[0m[1;33m,[0m [1;34m"r+b"[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m   2316[0m             [1;32melse[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 2317[1;33m                 [0mfp[0m [1;33m=[0m [0mbuiltins[0m[1;33m.[0m[0mopen[0m[1;33m([0m[0mfilename[0m[1;33m,[0m [1;34m"w+b"[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   2318[0m [1;33m[0m[0m
[0;32m   2319[0m         [1;32mtry[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '../images/w3_t1_gif/shot1.png'
FileNotFoundError: [Errno 2] No such file or directory: '../images/w3_t1_gif/shot1.png'

